--DROP CONSTRAINT
ALTER TABLE CINEMA DROP CONSTRAINT FK_CINEMA_COU_NUM CASCADE;
ALTER TABLE DIRECTOR DROP CONSTRAINT FK_DIRECTOR_DC_CODE CASCADE;
ALTER TABLE DIRECTOR DROP CONSTRAINT FK_DIRECTOR_C_NUM CASCADE;

--COUNTRY - CINEMA CONSTRAINT
ALTER TABLE CINEMA
ADD CONSTRAINT FK_CINEMA_COU_NUM FOREIGN KEY(COU_NUM) 
REFERENCES COUNTRY(COU_NUM);
--CINEMA - COUNTRY END

--DIRECTOR_CATEGORY - DIRECTOR CONSTRAINT
ALTER TABLE DIRECTOR
ADD CONSTRAINT FK_DIRECTOR_DC_CODE FOREIGN KEY(DC_CODE)
REFERENCES DIRECTOR_CATEGORY(DC_CODE);
--DIRECTOR_CATEGORY - DIRECTOR CONSTRAINT END

--CINEMA - DIRECTOR CONSTRAINT
ALTER TABLE DIRECTOR
ADD CONSTRAINT FK_DIRECTOR_C_NUM FOREIGN KEY(C_NUM)
REFERENCES CINEMA(C_NUM);
--CINEMA - DIRECTOR CONSTRAINT END

COMMIT;