--[1] MEMBER
DROP TABLE MEMBER
CASCADE CONSTRAINTS; 

SELECT * FROM MEMBER;

CREATE TABLE MEMBER(
	M_ID                 VARCHAR2(50) PRIMARY KEY,
	M_PASSWORD           VARCHAR2(128) NOT NULL,
	M_BIRTHDAY           DATE NULL,
	M_AUTHORITY          NUMBER NULL
);

INSERT INTO MEMBER
VALUES('kay', 'pwd', sysdate, 2)

--[2] REVIEW

DROP TABLE REVIEW
CASCADE CONSTRAINTS; 

SELECT * FROM REVIEW;

CREATE TABLE REVIEW(
	R_NUM                NUMBER PRIMARY KEY,
	C_NUM                NUMBER NOT NULL,
	M_ID                 VARCHAR2(50) NOT NULL,
	R_TITLE              VARCHAR2(100) NOT NULL,
	R_CONTENT            CLOB NOT NULL,
	R_DATE               DATE NOT NULL,
	R_COUNT              NUMBER NOT NULL,
	R_LIKE               NUMBER NOT NULL,
	R_PATH               VARCHAR2(100) NULL	
);

DROP SEQUENCE REVIEW_SEQ;

CREATE SEQUENCE REVIEW_SEQ
START WITH 1 INCREMENT BY 1;

ALTER TABLE REVIEW
ADD CONSTRAINT FK_REVIEW_M_ID FOREIGN KEY(M_ID) 
REFERENCES MEMBER(M_ID);
--
ALTER TABLE CINEMA
ADD CONSTRAINT FK_REVIEW_C_NUM FOREIGN KEY(C_NUM) 
REFERENCES CINEMA(C_NUM);
--
	INSERT INTO REVIEW
	VALUES( REVIEW_SEQ.NEXTVAL, 3, 'kay', 'TTTT', 'DDDD', SYSDATE, 0, 0, '')


--[3] REVIEW_COMMENT

DROP TABLE REVIEW_COMMENT
CASCADE CONSTRAINTS;

SELECT * FROM REVIEW_COMMENT;

CREATE TABLE REVIEW_COMMENT(
	RC_NUM               NUMBER PRIMARY KEY,
	M_ID                 VARCHAR2(50 BYTE) NOT NULL,
	RC_CONTENT           CLOB NOT NULL,
	RC_DATE              DATE NOT NULL,
	R_NUM                NUMBER NOT NULL
);

DROP SEQUENCE RC_NUM_SEQ;

CREATE SEQUENCE RC_NUM_SEQ
START WITH 1 INCREMENT BY 1;

ALTER TABLE REVIEW_COMMENT
ADD CONSTRAINT FK_REVIEW_COMMENT_M_ID FOREIGN KEY(M_ID) 
REFERENCES MEMBER(M_ID);


--[4] REVIEW_LIKE

DROP TABLE REVIEW_LIKE
CASCADE CONSTRAINTS; 

SELECT * FROM REVIEW_LIKE;

CREATE TABLE REVIEW_LIKE(
	M_ID                 VARCHAR2(50) NOT NULL,	
	R_NUM                NUMBER NOT NULL,
	RL_DATE              DATE NOT NULL
);

ALTER TABLE REVIEW_LIKE
ADD CONSTRAINT FK_REVIEW_LIKE_M_ID FOREIGN KEY(M_ID) 
REFERENCES MEMBER(M_ID);

ALTER TABLE REVIEW_LIKE
ADD CONSTRAINT FK_REVIEW_LIKE_R_NUM FOREIGN KEY(R_NUM) 
REFERENCES REVIEW(R_NUM);






